# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /setters
  name: network-setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  # If default VPC is enabled in same project can leave `network-ref` and `subnet-ref` 
  # as-is.
  # The name of the VPC in which to create this cluster
  network-ref: project/your-project-id/global/networks/default # kpt-set: project/${project-id}/global/networks/default
  # The reference to the subnet
  subnet-ref: project/your-project-id/regions/us-central1/subnetworks/default # kpt-set: project/${project-id}/regions/${location}/subnetworks/default
