apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: containerscanning.googleapis.com
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
spec:
  projectRef:
    external: projects/your-project-id # kpt-set: projects/${project-id}
