apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  # the name is restricted to ensure that there is only one
  # ConfigConnector resource installed in your cluster
  name: configconnector.core.cnrm.cloud.google.com
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn-live'
spec:
  mode: cluster
  googleServiceAccount: your-gsa@your-project-id.iam.gserviceaccount.com # kpt-set: ${gserviceaccount}@${project-id}.iam.gserviceaccount.com
